services:
  # Database PostgreSQL untuk penyimpanan permanen transaksi
  db:
    image: postgres:15-alpine
    container_name: qris_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: qrisdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init-db:/docker-entrypoint-initdb.d

  # # Redis untuk Caching Layer (Kunci optimasi latency p95)
  redis:
    image: redis:7-alpine
    container_name: qris_redis
    ports:
      - "6379:6379"

  # # RabbitMQ untuk Message Broker (Proses Asynchronous)
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: qris_rabbitmq
  #   ports:
  #     - "5672:5672"   # Port data
  #     - "15672:15672" # Port Dashboard (bisa dibuka di browser)
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # --- MONITORING STACK (ADDITION) ---

  # InfluxDB untuk menyimpan metrik hasil Load Test k6
  influxdb:
    image: influxdb:1.8-alpine
    container_name: qris_influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - influxdb_data:/var/lib/influxdb

  # Grafana untuk visualisasi grafik real-time
  grafana:
    image: grafana/grafana-oss
    container_name: qris_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  influxdb_data:
  grafana_data:
